import 'package:world_time/services/world_time.dart';

//// !==================================! LOCATION !==================================!
List<WorldTime> locations = [
  // Africa
  WorldTime(
    url: 'Africa/Accra',
    location: 'Accra',
    flag: 'ghana.png',
    countryCode: 'GH',
  ),
  WorldTime(
    url: 'Africa/Addis_Ababa',
    location: 'Addis Ababa',
    flag: 'ethiopia.png',
    countryCode: 'ET',
  ),
  WorldTime(
    url: 'Africa/Algiers',
    location: 'Algiers',
    flag: 'algeria.png',
    countryCode: 'DZ',
  ),
  WorldTime(
    url: 'Africa/Asmara',
    location: 'Asmara',
    flag: 'eritrea.png',
    countryCode: 'ER',
  ),
  WorldTime(
    url: 'Africa/Bamako',
    location: 'Bamako',
    flag: 'mali.png',
    countryCode: 'ML',
  ),
  WorldTime(
    url: 'Africa/Bangui',
    location: 'Bangui',
    flag: 'central_african_republic.png',
    countryCode: 'CF',
  ),
  WorldTime(
    url: 'Africa/Banjul',
    location: 'Banjul',
    flag: 'gambia.png',
    countryCode: 'GM',
  ),
  WorldTime(
    url: 'Africa/Bissau',
    location: 'Bissau',
    flag: 'guinea-bissau.png',
    countryCode: 'GW',
  ),
  WorldTime(
    url: 'Africa/Blantyre',
    location: 'Blantyre',
    flag: 'malawi.png',
    countryCode: 'MW',
  ),
  WorldTime(
    url: 'Africa/Brazzaville',
    location: 'Brazzaville',
    flag: 'republic_of_the_congo.png',
    countryCode: 'CG',
  ),
  WorldTime(
    url: 'Africa/Bujumbura',
    location: 'Bujumbura',
    flag: 'burundi.png',
    countryCode: 'BI',
  ),
  WorldTime(
    url: 'Africa/Cairo',
    location: 'Cairo',
    flag: 'egypt.png',
    countryCode: 'EG',
  ),
  WorldTime(
    url: 'Africa/Casablanca',
    location: 'Casablanca',
    flag: 'morocco.png',
    countryCode: 'MA',
  ),
  WorldTime(
    url: 'Africa/Ceuta',
    location: 'Ceuta',
    flag: 'spain.png',
    countryCode: 'ES',
  ),
  WorldTime(
    url: 'Africa/Conakry',
    location: 'Conakry',
    flag: 'guinea.png',
    countryCode: 'GN',
  ),
  WorldTime(
    url: 'Africa/Dakar',
    location: 'Dakar',
    flag: 'senegal.png',
    countryCode: 'SN',
  ),
  WorldTime(
    url: 'Africa/Dar_es_Salaam',
    location: 'Dar es Salaam',
    flag: 'tanzania.png',
    countryCode: 'TZ',
  ),
  WorldTime(
    url: 'Africa/Djibouti',
    location: 'Djibouti',
    flag: 'djibouti.png',
    countryCode: 'DJ',
  ),
  WorldTime(
    url: 'Africa/Douala',
    location: 'Douala',
    flag: 'cameroon.png',
    countryCode: 'CM',
  ),
  WorldTime(
    url: 'Africa/El_Aaiun',
    location: 'El Aaiun',
    flag: 'western_sahara.png',
    countryCode: 'EH',
  ),
  WorldTime(
    url: 'Africa/Freetown',
    location: 'Freetown',
    flag: 'sierra_leone.png',
    countryCode: 'SL',
  ),
  WorldTime(
    url: 'Africa/Gaborone',
    location: 'Gaborone',
    flag: 'botswana.png',
    countryCode: 'BW',
  ),
  WorldTime(
    url: 'Africa/Harare',
    location: 'Harare',
    flag: 'zimbabwe.png',
    countryCode: 'ZW',
  ),
  WorldTime(
    url: 'Africa/Johannesburg',
    location: 'Johannesburg',
    flag: 'south_africa.png',
    countryCode: 'ZA',
  ),
  WorldTime(
    url: 'Africa/Juba',
    location: 'Juba',
    flag: 'south_sudan.png',
    countryCode: 'SS',
  ),
  WorldTime(
    url: 'Africa/Kampala',
    location: 'Kampala',
    flag: 'uganda.png',
    countryCode: 'UG',
  ),
  WorldTime(
    url: 'Africa/Khartoum',
    location: 'Khartoum',
    flag: 'sudan.png',
    countryCode: 'SD',
  ),
  WorldTime(
    url: 'Africa/Kigali',
    location: 'Kigali',
    flag: 'rwanda.png',
    countryCode: 'RW',
  ),
  WorldTime(
    url: 'Africa/Kinshasa',
    location: 'Kinshasa',
    flag: 'democratic_republic_of_congo.png',
    countryCode: 'CD',
  ),
  WorldTime(
    url: 'Africa/Lagos',
    location: 'Lagos',
    flag: 'nigeria.png',
    countryCode: 'NG',
  ),
  WorldTime(
    url: 'Africa/Libreville',
    location: 'Libreville',
    flag: 'gabon.png',
    countryCode: 'GA',
  ),
  WorldTime(
    url: 'Africa/Lome',
    location: 'Lome',
    flag: 'togo.png',
    countryCode: 'TG',
  ),
  WorldTime(
    url: 'Africa/Luanda',
    location: 'Luanda',
    flag: 'angola.png',
    countryCode: 'AO',
  ),
  WorldTime(
    url: 'Africa/Lubumbashi',
    location: 'Lubumbashi',
    flag: 'democratic_republic_of_congo.png',
    countryCode: 'CD',
  ),
  WorldTime(
    url: 'Africa/Lusaka',
    location: 'Lusaka',
    flag: 'zambia.png',
    countryCode: 'ZM',
  ),
  WorldTime(
    url: 'Africa/Malabo',
    location: 'Malabo',
    flag: 'equatorial_guinea.png',
    countryCode: 'GQ',
  ),
  WorldTime(
    url: 'Africa/Maputo',
    location: 'Maputo',
    flag: 'mozambique.png',
    countryCode: 'MZ',
  ),
  WorldTime(
    url: 'Africa/Maseru',
    location: 'Maseru',
    flag: 'lesotho.png',
    countryCode: 'LS',
  ),
  WorldTime(
    url: 'Africa/Mbabane',
    location: 'Mbabane',
    flag: 'eswatini.png',
    countryCode: 'SZ',
  ),
  WorldTime(
    url: 'Africa/Mogadishu',
    location: 'Mogadishu',
    flag: 'somalia.png',
    countryCode: 'SO',
  ),
  WorldTime(
    url: 'Africa/Monrovia',
    location: 'Monrovia',
    flag: 'liberia.png',
    countryCode: 'LR',
  ),
  WorldTime(
    url: 'Africa/Nairobi',
    location: 'Nairobi',
    flag: 'kenya.png',
    countryCode: 'KE',
  ),
  WorldTime(
    url: 'Africa/Ndjamena',
    location: 'Ndjamena',
    flag: 'chad.png',
    countryCode: 'TD',
  ),
  WorldTime(
    url: 'Africa/Niamey',
    location: 'Niamey',
    flag: 'niger.png',
    countryCode: 'NE',
  ),
  WorldTime(
    url: 'Africa/Nouakchott',
    location: 'Nouakchott',
    flag: 'mauritania.png',
    countryCode: 'MR',
  ),
  WorldTime(
    url: 'Africa/Ouagadougou',
    location: 'Ouagadougou',
    flag: 'burkina_faso.png',
    countryCode: 'BF',
  ),
  WorldTime(
    url: 'Africa/Porto-Novo',
    location: 'Porto-Novo',
    flag: 'benin.png',
    countryCode: 'BJ',
  ),
  WorldTime(
    url: 'Africa/Sao_Tome',
    location: 'Sao Tome',
    flag: 'sao_tome_and_principe.png',
    countryCode: 'ST',
  ),
  WorldTime(
    url: 'Africa/Tripoli',
    location: 'Tripoli',
    flag: 'libya.png',
    countryCode: 'LY',
  ),
  WorldTime(
    url: 'Africa/Tunis',
    location: 'Tunis',
    flag: 'tunisia.png',
    countryCode: 'TN',
  ),
  WorldTime(
    url: 'Africa/Windhoek',
    location: 'Windhoek',
    flag: 'namibia.png',
    countryCode: 'NA',
  ),

  // America
  WorldTime(
    url: 'America/Adak',
    location: 'Adak',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Anchorage',
    location: 'Anchorage',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Anguilla',
    location: 'Anguilla',
    flag: 'anguilla.png',
    countryCode: 'AI',
  ),
  WorldTime(
    url: 'America/Antigua',
    location: 'Antigua',
    flag: 'antigua_and_barbuda.png',
    countryCode: 'AG',
  ),
  WorldTime(
    url: 'America/Araguaina',
    location: 'Araguaina',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Argentina/Buenos_Aires',
    location: 'Buenos Aires',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Catamarca',
    location: 'Catamarca',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Cordoba',
    location: 'Cordoba',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Jujuy',
    location: 'Jujuy',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/La_Rioja',
    location: 'La Rioja',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Mendoza',
    location: 'Mendoza',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Rio_Gallegos',
    location: 'Rio Gallegos',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Salta',
    location: 'Salta',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/San_Juan',
    location: 'San Juan',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/San_Luis',
    location: 'San Luis',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Tucuman',
    location: 'Tucuman',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Argentina/Ushuaia',
    location: 'Ushuaia',
    flag: 'argentina.png',
    countryCode: 'AR',
  ),
  WorldTime(
    url: 'America/Aruba',
    location: 'Aruba',
    flag: 'aruba.png',
    countryCode: 'AW',
  ),
  WorldTime(
    url: 'America/Asuncion',
    location: 'Asuncion',
    flag: 'paraguay.png',
    countryCode: 'PY',
  ),
  WorldTime(
    url: 'America/Atikokan',
    location: 'Atikokan',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Bahia',
    location: 'Bahia',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Bahia_Banderas',
    location: 'Bahia Banderas',
    flag: 'mexico.png',
    countryCode: 'MX',
  ),
  WorldTime(
    url: 'America/Barbados',
    location: 'Barbados',
    flag: 'barbados.png',
    countryCode: 'BB',
  ),
  WorldTime(
    url: 'America/Belem',
    location: 'Belem',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Belize',
    location: 'Belize',
    flag: 'belize.png',
    countryCode: 'BZ',
  ),
  WorldTime(
    url: 'America/Boa_Vista',
    location: 'Boa Vista',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Bogota',
    location: 'Bogota',
    flag: 'colombia.png',
    countryCode: 'CO',
  ),
  WorldTime(
    url: 'America/Boise',
    location: 'Boise',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Cambridge_Bay',
    location: 'Cambridge Bay',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Campo_Grande',
    location: 'Campo Grande',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Cancun',
    location: 'Cancun',
    flag: 'mexico.png',
    countryCode: 'MX',
  ),
  WorldTime(
    url: 'America/Caracas',
    location: 'Caracas',
    flag: 'venezuela.png',
    countryCode: 'VE',
  ),
  WorldTime(
    url: 'America/Cayenne',
    location: 'Cayenne',
    flag: 'french_guiana.png',
    countryCode: 'GF',
  ),
  WorldTime(
    url: 'America/Cayman',
    location: 'Cayman',
    flag: 'cayman_islands.png',
    countryCode: 'KY',
  ),
  WorldTime(
    url: 'America/Chicago',
    location: 'Chicago',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Chihuahua',
    location: 'Chihuahua',
    flag: 'mexico.png',
    countryCode: 'MX',
  ),
  WorldTime(
    url: 'America/Costa_Rica',
    location: 'Costa Rica',
    flag: 'costa_rica.png',
    countryCode: 'CR',
  ),
  WorldTime(
    url: 'America/Cuiaba',
    location: 'Cuiaba',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Curacao',
    location: 'Curacao',
    flag: 'curacao.png',
    countryCode: 'CW',
  ),
  WorldTime(
    url: 'America/Danmarkshavn',
    location: 'Danmarkshavn',
    flag: 'greenland.png',
    countryCode: 'GL',
  ),
  WorldTime(
    url: 'America/Dawson_Creek',
    location: 'Dawson Creek',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Denver',
    location: 'Denver',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Detroit',
    location: 'Detroit',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Edmonton',
    location: 'Edmonton',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/El_Salvador',
    location: 'El Salvador',
    flag: 'el_salvador.png',
    countryCode: 'SV',
  ),
  WorldTime(
    url: 'America/Fortaleza',
    location: 'Fortaleza',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Guatemala',
    location: 'Guatemala',
    flag: 'guatemala.png',
    countryCode: 'GT',
  ),
  WorldTime(
    url: 'America/Guayaquil',
    location: 'Guayaquil',
    flag: 'ecuador.png',
    countryCode: 'EC',
  ),
  WorldTime(
    url: 'America/Guyana',
    location: 'Guyana',
    flag: 'guyana.png',
    countryCode: 'GY',
  ),
  WorldTime(
    url: 'America/Halifax',
    location: 'Halifax',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Havana',
    location: 'Havana',
    flag: 'cuba.png',
    countryCode: 'CU',
  ),
  WorldTime(
    url: 'America/Indiana/Indianapolis',
    location: 'Indianapolis',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Jamaica',
    location: 'Jamaica',
    flag: 'jamaica.png',
    countryCode: 'JM',
  ),
  WorldTime(
    url: 'America/Juneau',
    location: 'Juneau',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Kentucky/Louisville',
    location: 'Louisville',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/La_Paz',
    location: 'La Paz',
    flag: 'bolivia.png',
    countryCode: 'BO',
  ),
  WorldTime(
    url: 'America/Lima',
    location: 'Lima',
    flag: 'peru.png',
    countryCode: 'PE',
  ),
  WorldTime(
    url: 'America/Los_Angeles',
    location: 'Los Angeles',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Managua',
    location: 'Managua',
    flag: 'nicaragua.png',
    countryCode: 'NI',
  ),
  WorldTime(
    url: 'America/Manaus',
    location: 'Manaus',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Martinique',
    location: 'Martinique',
    flag: 'martinique.png',
    countryCode: 'MQ',
  ),
  WorldTime(
    url: 'America/Mexico_City',
    location: 'Mexico City',
    flag: 'mexico.png',
    countryCode: 'MX',
  ),
  WorldTime(
    url: 'America/Miquelon',
    location: 'Miquelon',
    flag: 'st_pierre_and_miquelon.png',
    countryCode: 'PM',
  ),
  WorldTime(
    url: 'America/Montevideo',
    location: 'Montevideo',
    flag: 'uruguay.png',
    countryCode: 'UY',
  ),
  WorldTime(
    url: 'America/Nassau',
    location: 'Nassau',
    flag: 'bahamas.png',
    countryCode: 'BS',
  ),
  WorldTime(
    url: 'America/New_York',
    location: 'New York',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Nuuk',
    location: 'Nuuk',
    flag: 'greenland.png',
    countryCode: 'GL',
  ),
  WorldTime(
    url: 'America/Panama',
    location: 'Panama',
    flag: 'panama.png',
    countryCode: 'PA',
  ),
  WorldTime(
    url: 'America/Paramaribo',
    location: 'Paramaribo',
    flag: 'suriname.png',
    countryCode: 'SR',
  ),
  WorldTime(
    url: 'America/Phoenix',
    location: 'Phoenix',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'America/Port-au-Prince',
    location: 'Port-au-Prince',
    flag: 'haiti.png',
    countryCode: 'HT',
  ),
  WorldTime(
    url: 'America/Port_of_Spain',
    location: 'Port of Spain',
    flag: 'trinidad_and_tobago.png',
    countryCode: 'TT',
  ),
  WorldTime(
    url: 'America/Puerto_Rico',
    location: 'Puerto Rico',
    flag: 'puerto_rico.png',
    countryCode: 'PR',
  ),
  WorldTime(
    url: 'America/Punta_Arenas',
    location: 'Punta Arenas',
    flag: 'chile.png',
    countryCode: 'CL',
  ),
  WorldTime(
    url: 'America/Recife',
    location: 'Recife',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Regina',
    location: 'Regina',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Rio_Branco',
    location: 'Rio Branco',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Santiago',
    location: 'Santiago',
    flag: 'chile.png',
    countryCode: 'CL',
  ),
  WorldTime(
    url: 'America/Santo_Domingo',
    location: 'Santo Domingo',
    flag: 'dominican_republic.png',
    countryCode: 'DO',
  ),
  WorldTime(
    url: 'America/Sao_Paulo',
    location: 'Sao Paulo',
    flag: 'brazil.png',
    countryCode: 'BR',
  ),
  WorldTime(
    url: 'America/Scoresbysund',
    location: 'Scoresbysund',
    flag: 'greenland.png',
    countryCode: 'GL',
  ),
  WorldTime(
    url: 'America/Tegucigalpa',
    location: 'Tegucigalpa',
    flag: 'honduras.png',
    countryCode: 'HN',
  ),
  WorldTime(
    url: 'America/Thule',
    location: 'Thule',
    flag: 'greenland.png',
    countryCode: 'GL',
  ),
  WorldTime(
    url: 'America/Tijuana',
    location: 'Tijuana',
    flag: 'mexico.png',
    countryCode: 'MX',
  ),
  WorldTime(
    url: 'America/Toronto',
    location: 'Toronto',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Vancouver',
    location: 'Vancouver',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Whitehorse',
    location: 'Whitehorse',
    flag: 'canada.png',
    countryCode: 'CA',
  ),
  WorldTime(
    url: 'America/Winnipeg',
    location: 'Winnipeg',
    flag: 'canada.png',
    countryCode: 'CA',
  ),

  // Antarctica
  WorldTime(
    url: 'Antarctica/Casey',
    location: 'Casey',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Davis',
    location: 'Davis',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/DumontDUrville',
    location: 'DumontDUrville',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Macquarie',
    location: 'Macquarie',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Antarctica/Mawson',
    location: 'Mawson',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/McMurdo',
    location: 'McMurdo',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Palmer',
    location: 'Palmer',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Rothera',
    location: 'Rothera',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Syowa',
    location: 'Syowa',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Troll',
    location: 'Troll',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),
  WorldTime(
    url: 'Antarctica/Vostok',
    location: 'Vostok',
    flag: 'antarctica.png',
    countryCode: 'AQ',
  ),

  // Asia
  WorldTime(
    url: 'Asia/Almaty',
    location: 'Almaty',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Amman',
    location: 'Amman',
    flag: 'jordan.png',
    countryCode: 'JO',
  ),
  WorldTime(
    url: 'Asia/Anadyr',
    location: 'Anadyr',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Aqtau',
    location: 'Aqtau',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Aqtobe',
    location: 'Aqtobe',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Ashgabat',
    location: 'Ashgabat',
    flag: 'turkmenistan.png',
    countryCode: 'TM',
  ),
  WorldTime(
    url: 'Asia/Atyrau',
    location: 'Atyrau',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Baghdad',
    location: 'Baghdad',
    flag: 'iraq.png',
    countryCode: 'IQ',
  ),
  WorldTime(
    url: 'Asia/Baku',
    location: 'Baku',
    flag: 'azerbaijan.png',
    countryCode: 'AZ',
  ),
  WorldTime(
    url: 'Asia/Bangkok',
    location: 'Bangkok',
    flag: 'thailand.png',
    countryCode: 'TH',
  ),
  WorldTime(
    url: 'Asia/Barnaul',
    location: 'Barnaul',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Beirut',
    location: 'Beirut',
    flag: 'lebanon.png',
    countryCode: 'LB',
  ),
  WorldTime(
    url: 'Asia/Bishkek',
    location: 'Bishkek',
    flag: 'kyrgyzstan.png',
    countryCode: 'KG',
  ),
  WorldTime(
    url: 'Asia/Brunei',
    location: 'Brunei',
    flag: 'brunei.png',
    countryCode: 'BN',
  ),
  WorldTime(
    url: 'Asia/Chita',
    location: 'Chita',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Choibalsan',
    location: 'Choibalsan',
    flag: 'mongolia.png',
    countryCode: 'MN',
  ),
  WorldTime(
    url: 'Asia/Colombo',
    location: 'Colombo',
    flag: 'sri_lanka.png',
    countryCode: 'LK',
  ),
  WorldTime(
    url: 'Asia/Damascus',
    location: 'Damascus',
    flag: 'syria.png',
    countryCode: 'SY',
  ),
  WorldTime(
    url: 'Asia/Dhaka',
    location: 'Dhaka',
    flag: 'bangladesh.png',
    countryCode: 'BD',
  ),
  WorldTime(
    url: 'Asia/Dili',
    location: 'Dili',
    flag: 'timor-leste.png',
    countryCode: 'TL',
  ),
  WorldTime(
    url: 'Asia/Dubai',
    location: 'Dubai',
    flag: 'uae.png',
    countryCode: 'AE',
  ),
  WorldTime(
    url: 'Asia/Dushanbe',
    location: 'Dushanbe',
    flag: 'tajikistan.png',
    countryCode: 'TJ',
  ),
  WorldTime(
    url: 'Asia/Famagusta',
    location: 'Famagusta',
    flag: 'cyprus.png',
    countryCode: 'CY',
  ),
  WorldTime(
    url: 'Asia/Gaza',
    location: 'Gaza',
    flag: 'palestine.png',
    countryCode: 'PS',
  ),
  WorldTime(
    url: 'Asia/Hebron',
    location: 'Hebron',
    flag: 'palestine.png',
    countryCode: 'PS',
  ),
  WorldTime(
    url: 'Asia/Ho_Chi_Minh',
    location: 'Ho Chi Minh',
    flag: 'vietnam.png',
    countryCode: 'VN',
  ),
  WorldTime(
    url: 'Asia/Hong_Kong',
    location: 'Hong Kong',
    flag: 'hong_kong.png',
    countryCode: 'HK',
  ),
  WorldTime(
    url: 'Asia/Hovd',
    location: 'Hovd',
    flag: 'mongolia.png',
    countryCode: 'MN',
  ),
  WorldTime(
    url: 'Asia/Irkutsk',
    location: 'Irkutsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Jakarta',
    location: 'Jakarta',
    flag: 'indonesia.png',
    countryCode: 'ID',
  ),
  WorldTime(
    url: 'Asia/Jayapura',
    location: 'Jayapura',
    flag: 'indonesia.png',
    countryCode: 'ID',
  ),
  WorldTime(
    url: 'Asia/Jerusalem',
    location: 'Jerusalem',
    flag: 'israel.png',
    countryCode: 'IL',
  ),
  WorldTime(
    url: 'Asia/Kabul',
    location: 'Kabul',
    flag: 'afghanistan.png',
    countryCode: 'AF',
  ),
  WorldTime(
    url: 'Asia/Kamchatka',
    location: 'Kamchatka',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Karachi',
    location: 'Karachi',
    flag: 'pakistan.png',
    countryCode: 'PK',
  ),
  WorldTime(
    url: 'Asia/Kathmandu',
    location: 'Kathmandu',
    flag: 'nepal.png',
    countryCode: 'NP',
  ),
  WorldTime(
    url: 'Asia/Khandyga',
    location: 'Khandyga',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Kolkata',
    location: 'Kolkata',
    flag: 'india.png',
    countryCode: 'IN',
  ),
  WorldTime(
    url: 'Asia/Krasnoyarsk',
    location: 'Krasnoyarsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Kuala_Lumpur',
    location: 'Kuala Lumpur',
    flag: 'malaysia.png',
    countryCode: 'MY',
  ),
  WorldTime(
    url: 'Asia/Kuching',
    location: 'Kuching',
    flag: 'malaysia.png',
    countryCode: 'MY',
  ),
  WorldTime(
    url: 'Asia/Kuwait',
    location: 'Kuwait',
    flag: 'kuwait.png',
    countryCode: 'KW',
  ),
  WorldTime(
    url: 'Asia/Macau',
    location: 'Macau',
    flag: 'macau.png',
    countryCode: 'MO',
  ),
  WorldTime(
    url: 'Asia/Magadan',
    location: 'Magadan',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Makassar',
    location: 'Makassar',
    flag: 'indonesia.png',
    countryCode: 'ID',
  ),
  WorldTime(
    url: 'Asia/Manila',
    location: 'Manila',
    flag: 'philippines.png',
    countryCode: 'PH',
  ),
  WorldTime(
    url: 'Asia/Muscat',
    location: 'Muscat',
    flag: 'oman.png',
    countryCode: 'OM',
  ),
  WorldTime(
    url: 'Asia/Nicosia',
    location: 'Nicosia',
    flag: 'cyprus.png',
    countryCode: 'CY',
  ),
  WorldTime(
    url: 'Asia/Novokuznetsk',
    location: 'Novokuznetsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Novosibirsk',
    location: 'Novosibirsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Omsk',
    location: 'Omsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Oral',
    location: 'Oral',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Phnom_Penh',
    location: 'Phnom Penh',
    flag: 'cambodia.png',
    countryCode: 'KH',
  ),
  WorldTime(
    url: 'Asia/Pontianak',
    location: 'Pontianak',
    flag: 'indonesia.png',
    countryCode: 'ID',
  ),
  WorldTime(
    url: 'Asia/Pyongyang',
    location: 'Pyongyang',
    flag: 'north_korea.png',
    countryCode: 'KP',
  ),
  WorldTime(
    url: 'Asia/Qatar',
    location: 'Qatar',
    flag: 'qatar.png',
    countryCode: 'QA',
  ),
  WorldTime(
    url: 'Asia/Qostanay',
    location: 'Qostanay',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Qyzylorda',
    location: 'Qyzylorda',
    flag: 'kazakhstan.png',
    countryCode: 'KZ',
  ),
  WorldTime(
    url: 'Asia/Riyadh',
    location: 'Riyadh',
    flag: 'saudi_arabia.png',
    countryCode: 'SA',
  ),
  WorldTime(
    url: 'Asia/Sakhalin',
    location: 'Sakhalin',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Samarkand',
    location: 'Samarkand',
    flag: 'uzbekistan.png',
    countryCode: 'UZ',
  ),
  WorldTime(
    url: 'Asia/Seoul',
    location: 'Seoul',
    flag: 'south_korea.png',
    countryCode: 'KR',
  ),
  WorldTime(
    url: 'Asia/Shanghai',
    location: 'Shanghai',
    flag: 'china.png',
    countryCode: 'CN',
  ),
  WorldTime(
    url: 'Asia/Singapore',
    location: 'Singapore',
    flag: 'singapore.png',
    countryCode: 'SG',
  ),
  WorldTime(
    url: 'Asia/Srednekolymsk',
    location: 'Srednekolymsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Taipei',
    location: 'Taipei',
    flag: 'taiwan.png',
    countryCode: 'TW',
  ),
  WorldTime(
    url: 'Asia/Tashkent',
    location: 'Tashkent',
    flag: 'uzbekistan.png',
    countryCode: 'UZ',
  ),
  WorldTime(
    url: 'Asia/Tbilisi',
    location: 'Tbilisi',
    flag: 'georgia.png',
    countryCode: 'GE',
  ),
  WorldTime(
    url: 'Asia/Tehran',
    location: 'Tehran',
    flag: 'iran.png',
    countryCode: 'IR',
  ),
  WorldTime(
    url: 'Asia/Thimphu',
    location: 'Thimphu',
    flag: 'bhutan.png',
    countryCode: 'BT',
  ),
  WorldTime(
    url: 'Asia/Tokyo',
    location: 'Tokyo',
    flag: 'japan.png',
    countryCode: 'JP',
  ),
  WorldTime(
    url: 'Asia/Tomsk',
    location: 'Tomsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Ulaanbaatar',
    location: 'Ulaanbaatar',
    flag: 'mongolia.png',
    countryCode: 'MN',
  ),
  WorldTime(
    url: 'Asia/Urumqi',
    location: 'Urumqi',
    flag: 'china.png',
    countryCode: 'CN',
  ),
  WorldTime(
    url: 'Asia/Vientiane',
    location: 'Vientiane',
    flag: 'laos.png',
    countryCode: 'LA',
  ),
  WorldTime(
    url: 'Asia/Vladivostok',
    location: 'Vladivostok',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Yakutsk',
    location: 'Yakutsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Yangon',
    location: 'Yangon',
    flag: 'myanmar.png',
    countryCode: 'MM',
  ),
  WorldTime(
    url: 'Asia/Yekaterinburg',
    location: 'Yekaterinburg',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Asia/Yerevan',
    location: 'Yerevan',
    flag: 'armenia.png',
    countryCode: 'AM',
  ),

  // Atlantic
  WorldTime(
    url: 'Atlantic/Azores',
    location: 'Azores',
    flag: 'portugal.png',
    countryCode: 'PT',
  ),
  WorldTime(
    url: 'Atlantic/Bermuda',
    location: 'Bermuda',
    flag: 'bermuda.png',
    countryCode: 'BM',
  ),
  WorldTime(
    url: 'Atlantic/Canary',
    location: 'Canary',
    flag: 'spain.png',
    countryCode: 'ES',
  ),
  WorldTime(
    url: 'Atlantic/Cape_Verde',
    location: 'Cape Verde',
    flag: 'cape_verde.png',
    countryCode: 'CV',
  ),
  WorldTime(
    url: 'Atlantic/Faroe',
    location: 'Faroe',
    flag: 'faroe_islands.png',
    countryCode: 'FO',
  ),
  WorldTime(
    url: 'Atlantic/Madeira',
    location: 'Madeira',
    flag: 'portugal.png',
    countryCode: 'PT',
  ),
  WorldTime(
    url: 'Atlantic/Reykjavik',
    location: 'Reykjavik',
    flag: 'iceland.png',
    countryCode: 'IS',
  ),
  WorldTime(
    url: 'Atlantic/South_Georgia',
    location: 'South Georgia',
    flag: 'south_georgia.png',
    countryCode: 'GS',
  ),
  WorldTime(
    url: 'Atlantic/St_Helena',
    location: 'St Helena',
    flag: 'st_helena.png',
    countryCode: 'SH',
  ),
  WorldTime(
    url: 'Atlantic/Stanley',
    location: 'Stanley',
    flag: 'falkland_islands.png',
    countryCode: 'FK',
  ),

  // Australia
  WorldTime(
    url: 'Australia/Adelaide',
    location: 'Adelaide',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Brisbane',
    location: 'Brisbane',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Broken_Hill',
    location: 'Broken Hill',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Currie',
    location: 'Currie',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Darwin',
    location: 'Darwin',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Eucla',
    location: 'Eucla',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Hobart',
    location: 'Hobart',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Lindeman',
    location: 'Lindeman',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Lord_Howe',
    location: 'Lord Howe',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Melbourne',
    location: 'Melbourne',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Perth',
    location: 'Perth',
    flag: 'australia.png',
    countryCode: 'AU',
  ),
  WorldTime(
    url: 'Australia/Sydney',
    location: 'Sydney',
    flag: 'australia.png',
    countryCode: 'AU',
  ),

  // Europe
  WorldTime(
    url: 'Europe/Amsterdam',
    location: 'Amsterdam',
    flag: 'netherlands.png',
    countryCode: 'NL',
  ),
  WorldTime(
    url: 'Europe/Andorra',
    location: 'Andorra',
    flag: 'andorra.png',
    countryCode: 'AD',
  ),
  WorldTime(
    url: 'Europe/Astrakhan',
    location: 'Astrakhan',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Athens',
    location: 'Athens',
    flag: 'greece.png',
    countryCode: 'GR',
  ),
  WorldTime(
    url: 'Europe/Belgrade',
    location: 'Belgrade',
    flag: 'serbia.png',
    countryCode: 'RS',
  ),
  WorldTime(
    url: 'Europe/Berlin',
    location: 'Berlin',
    flag: 'germany.png',
    countryCode: 'DE',
  ),
  WorldTime(
    url: 'Europe/Bratislava',
    location: 'Bratislava',
    flag: 'slovakia.png',
    countryCode: 'SK',
  ),
  WorldTime(
    url: 'Europe/Brussels',
    location: 'Brussels',
    flag: 'belgium.png',
    countryCode: 'BE',
  ),
  WorldTime(
    url: 'Europe/Bucharest',
    location: 'Bucharest',
    flag: 'romania.png',
    countryCode: 'RO',
  ),
  WorldTime(
    url: 'Europe/Budapest',
    location: 'Budapest',
    flag: 'hungary.png',
    countryCode: 'HU',
  ),
  WorldTime(
    url: 'Europe/Busingen',
    location: 'Busingen',
    flag: 'germany.png',
    countryCode: 'DE',
  ),
  WorldTime(
    url: 'Europe/Chisinau',
    location: 'Chisinau',
    flag: 'moldova.png',
    countryCode: 'MD',
  ),
  WorldTime(
    url: 'Europe/Copenhagen',
    location: 'Copenhagen',
    flag: 'denmark.png',
    countryCode: 'DK',
  ),
  WorldTime(
    url: 'Europe/Dublin',
    location: 'Dublin',
    flag: 'ireland.png',
    countryCode: 'IE',
  ),
  WorldTime(
    url: 'Europe/Gibraltar',
    location: 'Gibraltar',
    flag: 'gibraltar.png',
    countryCode: 'GI',
  ),
  WorldTime(
    url: 'Europe/Guernsey',
    location: 'Guernsey',
    flag: 'guernsey.png',
    countryCode: 'GG',
  ),
  WorldTime(
    url: 'Europe/Helsinki',
    location: 'Helsinki',
    flag: 'finland.png',
    countryCode: 'FI',
  ),
  WorldTime(
    url: 'Europe/Isle_of_Man',
    location: 'Isle of Man',
    flag: 'isle_of_man.png',
    countryCode: 'IM',
  ),
  WorldTime(
    url: 'Europe/Istanbul',
    location: 'Istanbul',
    flag: 'turkey.png',
    countryCode: 'TR',
  ),
  WorldTime(
    url: 'Europe/Jersey',
    location: 'Jersey',
    flag: 'jersey.png',
    countryCode: 'JE',
  ),
  WorldTime(
    url: 'Europe/Kaliningrad',
    location: 'Kaliningrad',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Kiev',
    location: 'Kiev',
    flag: 'ukraine.png',
    countryCode: 'UA',
  ),
  WorldTime(
    url: 'Europe/Kirov',
    location: 'Kirov',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Lisbon',
    location: 'Lisbon',
    flag: 'portugal.png',
    countryCode: 'PT',
  ),
  WorldTime(
    url: 'Europe/Ljubljana',
    location: 'Ljubljana',
    flag: 'slovenia.png',
    countryCode: 'SI',
  ),
  WorldTime(
    url: 'Europe/London',
    location: 'London',
    flag: 'uk.png',
    countryCode: 'GB',
  ),
  WorldTime(
    url: 'Europe/Luxembourg',
    location: 'Luxembourg',
    flag: 'luxembourg.png',
    countryCode: 'LU',
  ),
  WorldTime(
    url: 'Europe/Madrid',
    location: 'Madrid',
    flag: 'spain.png',
    countryCode: 'ES',
  ),
  WorldTime(
    url: 'Europe/Malta',
    location: 'Malta',
    flag: 'malta.png',
    countryCode: 'MT',
  ),
  WorldTime(
    url: 'Europe/Mariehamn',
    location: 'Mariehamn',
    flag: 'aland_islands.png',
    countryCode: 'AX',
  ),
  WorldTime(
    url: 'Europe/Minsk',
    location: 'Minsk',
    flag: 'belarus.png',
    countryCode: 'BY',
  ),
  WorldTime(
    url: 'Europe/Monaco',
    location: 'Monaco',
    flag: 'monaco.png',
    countryCode: 'MC',
  ),
  WorldTime(
    url: 'Europe/Moscow',
    location: 'Moscow',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Oslo',
    location: 'Oslo',
    flag: 'norway.png',
    countryCode: 'NO',
  ),
  WorldTime(
    url: 'Europe/Paris',
    location: 'Paris',
    flag: 'france.png',
    countryCode: 'FR',
  ),
  WorldTime(
    url: 'Europe/Podgorica',
    location: 'Podgorica',
    flag: 'montenegro.png',
    countryCode: 'ME',
  ),
  WorldTime(
    url: 'Europe/Prague',
    location: 'Prague',
    flag: 'czech_republic.png',
    countryCode: 'CZ',
  ),
  WorldTime(
    url: 'Europe/Riga',
    location: 'Riga',
    flag: 'latvia.png',
    countryCode: 'LV',
  ),
  WorldTime(
    url: 'Europe/Rome',
    location: 'Rome',
    flag: 'italy.png',
    countryCode: 'IT',
  ),
  WorldTime(
    url: 'Europe/Samara',
    location: 'Samara',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/San_Marino',
    location: 'San Marino',
    flag: 'san_marino.png',
    countryCode: 'SM',
  ),
  WorldTime(
    url: 'Europe/Sarajevo',
    location: 'Sarajevo',
    flag: 'bosnia_and_herzegovina.png',
    countryCode: 'BA',
  ),
  WorldTime(
    url: 'Europe/Saratov',
    location: 'Saratov',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Simferopol',
    location: 'Simferopol',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Skopje',
    location: 'Skopje',
    flag: 'north_macedonia.png',
    countryCode: 'MK',
  ),
  WorldTime(
    url: 'Europe/Sofia',
    location: 'Sofia',
    flag: 'bulgaria.png',
    countryCode: 'BG',
  ),
  WorldTime(
    url: 'Europe/Stockholm',
    location: 'Stockholm',
    flag: 'sweden.png',
    countryCode: 'SE',
  ),
  WorldTime(
    url: 'Europe/Tallinn',
    location: 'Tallinn',
    flag: 'estonia.png',
    countryCode: 'EE',
  ),
  WorldTime(
    url: 'Europe/Tirane',
    location: 'Tirane',
    flag: 'albania.png',
    countryCode: 'AL',
  ),
  WorldTime(
    url: 'Europe/Ulyanovsk',
    location: 'Ulyanovsk',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Vaduz',
    location: 'Vaduz',
    flag: 'liechtenstein.png',
    countryCode: 'LI',
  ),
  WorldTime(
    url: 'Europe/Vatican',
    location: 'Vatican',
    flag: 'vatican_city.png',
    countryCode: 'VA',
  ),
  WorldTime(
    url: 'Europe/Vienna',
    location: 'Vienna',
    flag: 'austria.png',
    countryCode: 'AT',
  ),
  WorldTime(
    url: 'Europe/Vilnius',
    location: 'Vilnius',
    flag: 'lithuania.png',
    countryCode: 'LT',
  ),
  WorldTime(
    url: 'Europe/Volgograd',
    location: 'Volgograd',
    flag: 'russia.png',
    countryCode: 'RU',
  ),
  WorldTime(
    url: 'Europe/Warsaw',
    location: 'Warsaw',
    flag: 'poland.png',
    countryCode: 'PL',
  ),
  WorldTime(
    url: 'Europe/Zagreb',
    location: 'Zagreb',
    flag: 'croatia.png',
    countryCode: 'HR',
  ),
  WorldTime(
    url: 'Europe/Zurich',
    location: 'Zurich',
    flag: 'switzerland.png',
    countryCode: 'CH',
  ),

  // Indian Ocean
  WorldTime(
    url: 'Indian/Antananarivo',
    location: 'Antananarivo',
    flag: 'madagascar.png',
    countryCode: 'MG',
  ),
  WorldTime(
    url: 'Indian/Chagos',
    location: 'Chagos',
    flag: 'british_indian_ocean_territory.png',
    countryCode: 'IO',
  ),
  WorldTime(
    url: 'Indian/Christmas',
    location: 'Christmas',
    flag: 'christmas_island.png',
    countryCode: 'CX',
  ),
  WorldTime(
    url: 'Indian/Cocos',
    location: 'Cocos',
    flag: 'cocos_islands.png',
    countryCode: 'CC',
  ),
  WorldTime(
    url: 'Indian/Comoro',
    location: 'Comoro',
    flag: 'comoros.png',
    countryCode: 'KM',
  ),
  WorldTime(
    url: 'Indian/Kerguelen',
    location: 'Kerguelen',
    flag: 'french_southern_territories.png',
    countryCode: 'TF',
  ),
  WorldTime(
    url: 'Indian/Mahe',
    location: 'Mahe',
    flag: 'seychelles.png',
    countryCode: 'SC',
  ),
  WorldTime(
    url: 'Indian/Maldives',
    location: 'Maldives',
    flag: 'maldives.png',
    countryCode: 'MV',
  ),
  WorldTime(
    url: 'Indian/Mauritius',
    location: 'Mauritius',
    flag: 'mauritius.png',
    countryCode: 'MU',
  ),
  WorldTime(
    url: 'Indian/Mayotte',
    location: 'Mayotte',
    flag: 'mayotte.png',
    countryCode: 'YT',
  ),
  WorldTime(
    url: 'Indian/Reunion',
    location: 'Reunion',
    flag: 'reunion.png',
    countryCode: 'RE',
  ),

  // Pacific
  WorldTime(
    url: 'Pacific/Apia',
    location: 'Apia',
    flag: 'samoa.png',
    countryCode: 'WS',
  ),
  WorldTime(
    url: 'Pacific/Auckland',
    location: 'Auckland',
    flag: 'new_zealand.png',
    countryCode: 'NZ',
  ),
  WorldTime(
    url: 'Pacific/Bougainville',
    location: 'Bougainville',
    flag: 'papua_new_guinea.png',
    countryCode: 'PG',
  ),
  WorldTime(
    url: 'Pacific/Chatham',
    location: 'Chatham',
    flag: 'new_zealand.png',
    countryCode: 'NZ',
  ),
  WorldTime(
    url: 'Pacific/Chuuk',
    location: 'Chuuk',
    flag: 'micronesia.png',
    countryCode: 'FM',
  ),
  WorldTime(
    url: 'Pacific/Easter',
    location: 'Easter',
    flag: 'chile.png',
    countryCode: 'CL',
  ),
  WorldTime(
    url: 'Pacific/Efate',
    location: 'Efate',
    flag: 'vanuatu.png',
    countryCode: 'VU',
  ),
  WorldTime(
    url: 'Pacific/Fakaofo',
    location: 'Fakaofo',
    flag: 'tokelau.png',
    countryCode: 'TK',
  ),
  WorldTime(
    url: 'Pacific/Fiji',
    location: 'Fiji',
    flag: 'fiji.png',
    countryCode: 'FJ',
  ),
  WorldTime(
    url: 'Pacific/Funafuti',
    location: 'Funafuti',
    flag: 'tuvalu.png',
    countryCode: 'TV',
  ),
  WorldTime(
    url: 'Pacific/Galapagos',
    location: 'Galapagos',
    flag: 'ecuador.png',
    countryCode: 'EC',
  ),
  WorldTime(
    url: 'Pacific/Gambier',
    location: 'Gambier',
    flag: 'french_polynesia.png',
    countryCode: 'PF',
  ),
  WorldTime(
    url: 'Pacific/Guadalcanal',
    location: 'Guadalcanal',
    flag: 'solomon_islands.png',
    countryCode: 'SB',
  ),
  WorldTime(
    url: 'Pacific/Guam',
    location: 'Guam',
    flag: 'guam.png',
    countryCode: 'GU',
  ),
  WorldTime(
    url: 'Pacific/Honolulu',
    location: 'Honolulu',
    flag: 'usa.png',
    countryCode: 'US',
  ),
  WorldTime(
    url: 'Pacific/Kiritimati',
    location: 'Kiritimati',
    flag: 'kiribati.png',
    countryCode: 'KI',
  ),
  WorldTime(
    url: 'Pacific/Kosrae',
    location: 'Kosrae',
    flag: 'micronesia.png',
    countryCode: 'FM',
  ),
  WorldTime(
    url: 'Pacific/Kwajalein',
    location: 'Kwajalein',
    flag: 'marshall_islands.png',
    countryCode: 'MH',
  ),
  WorldTime(
    url: 'Pacific/Majuro',
    location: 'Majuro',
    flag: 'marshall_islands.png',
    countryCode: 'MH',
  ),
  WorldTime(
    url: 'Pacific/Marquesas',
    location: 'Marquesas',
    flag: 'french_polynesia.png',
    countryCode: 'PF',
  ),
  WorldTime(
    url: 'Pacific/Nauru',
    location: 'Nauru',
    flag: 'nauru.png',
    countryCode: 'NR',
  ),
  WorldTime(
    url: 'Pacific/Niue',
    location: 'Niue',
    flag: 'niue.png',
    countryCode: 'NU',
  ),
  WorldTime(
    url: 'Pacific/Norfolk',
    location: 'Norfolk',
    flag: 'norfolk_island.png',
    countryCode: 'NF',
  ),
  WorldTime(
    url: 'Pacific/Noumea',
    location: 'Noumea',
    flag: 'new_caledonia.png',
    countryCode: 'NC',
  ),
  WorldTime(
    url: 'Pacific/Pago_Pago',
    location: 'Pago Pago',
    flag: 'american_samoa.png',
    countryCode: 'AS',
  ),
  WorldTime(
    url: 'Pacific/Palau',
    location: 'Palau',
    flag: 'palau.png',
    countryCode: 'PW',
  ),
  WorldTime(
    url: 'Pacific/Pitcairn',
    location: 'Pitcairn',
    flag: 'pitcairn_islands.png',
    countryCode: 'PN',
  ),
  WorldTime(
    url: 'Pacific/Pohnpei',
    location: 'Pohnpei',
    flag: 'micronesia.png',
    countryCode: 'FM',
  ),
  WorldTime(
    url: 'Pacific/Port_Moresby',
    location: 'Port Moresby',
    flag: 'papua_new_guinea.png',
    countryCode: 'PG',
  ),
  WorldTime(
    url: 'Pacific/Rarotonga',
    location: 'Rarotonga',
    flag: 'cook_islands.png',
    countryCode: 'CK',
  ),
  WorldTime(
    url: 'Pacific/Saipan',
    location: 'Saipan',
    flag: 'northern_mariana_islands.png',
    countryCode: 'MP',
  ),
  WorldTime(
    url: 'Pacific/Tahiti',
    location: 'Tahiti',
    flag: 'french_polynesia.png',
    countryCode: 'PF',
  ),
  WorldTime(
    url: 'Pacific/Tarawa',
    location: 'Tarawa',
    flag: 'kiribati.png',
    countryCode: 'KI',
  ),
  WorldTime(
    url: 'Pacific/Tongatapu',
    location: 'Tongatapu',
    flag: 'tonga.png',
    countryCode: 'TO',
  ),
  WorldTime(
    url: 'Pacific/Wake',
    location: 'Wake',
    flag: 'wake_island.png',
    countryCode: 'UM',
  ),
  WorldTime(
    url: 'Pacific/Wallis',
    location: 'Wallis',
    flag: 'wallis_and_futuna.png',
    countryCode: 'WF',
  ),
];
